version: '3.5'

services:
  game7Api:
    image: node:latest
    volumes:
      - ./:/app
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/app_db?schema=public
    depends_on:
      - postgres
    working_dir: /app
    command: bash -c "yarn && yarn dev"
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db